set_property PACKAGE_PIN L27 [get_ports clk_p]
set_property PACKAGE_PIN P10 [get_ports clk_out_10]

set_property IOSTANDARD LVCMOS18 [get_ports clk_out_10]

set_property PACKAGE_PIN AG14 [get_ports {o_led[0]}]
set_property PACKAGE_PIN AF13 [get_ports {o_led[1]}]
set_property PACKAGE_PIN AE13 [get_ports {o_led[2]}]
set_property PACKAGE_PIN AJ14 [get_ports {o_led[3]}]
set_property PACKAGE_PIN AJ15 [get_ports {o_led[4]}]
set_property PACKAGE_PIN AH13 [get_ports {o_led[5]}]
set_property PACKAGE_PIN AH14 [get_ports {o_led[6]}]
set_property PACKAGE_PIN AL12 [get_ports {o_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[0]}]