# set_property PACKAGE_PIN G27 [get_ports clk_p]
# set_property PACKAGE_PIN P10 [get_ports clk_out_10]

# set_property IOSTANDARD LVCMOS18 [get_ports clk_out_10]

set_property PACKAGE_PIN AG14 [get_ports {o_led[0]}]
set_property PACKAGE_PIN AF13 [get_ports {o_led[1]}]
set_property PACKAGE_PIN AE13 [get_ports {o_led[2]}]
set_property PACKAGE_PIN AJ14 [get_ports {o_led[3]}]
set_property PACKAGE_PIN AJ15 [get_ports {o_led[4]}]
set_property PACKAGE_PIN AH13 [get_ports {o_led[5]}]
set_property PACKAGE_PIN AH14 [get_ports {o_led[6]}]
set_property PACKAGE_PIN AL12 [get_ports {o_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[0]}]
set_property PACKAGE_PIN P10 [get_ports clk_10mhz_in]
set_property IOSTANDARD LVCMOS12 [get_ports clk_10mhz_in]
set_property PACKAGE_PIN P9 [get_ports clk_10mhz_out]
set_property IOSTANDARD LVCMOS12 [get_ports clk_10mhz_out]
# set_property PACKAGE_PIN J27 [get_ports clk_gt_external_p]
set_property PACKAGE_PIN L27 [get_ports clk_gt_internal_p]

set_property IOSTANDARD DIFF_SSTL12 [get_ports user_si570_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports user_si570_clk_n]


set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets bd/zcu102_zpulse_i/clk_wiz_2/inst/clk_out1_zcu102_zpulse_clk_wiz_2_0]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets bd/zcu102_zpulse_i/clk_wiz_2/inst/clk_out1_zcu102_zpulse_clk_wiz_0_0]